version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: pw1tt
      RABBITMQ_DEFAULT_PASS: securerabbitmqpassword
    ports:
      - "5672:5672" # RabbitMQ main port
      - "15672:15672" # RabbitMQ management UI
    volumes:
      - pw1_rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:latest
    command: redis-server --requirepass secureredispassword
    ports:
      - "6379:6379"
    volumes:
      - pw1_redis_data:/data

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: pw1tt
      POSTGRES_PASSWORD: securepostgrespassword
      POSTGRES_DB: blackboard
    ports:
      - "5432:5432"
    volumes:
      - pw1_postgres_data:/var/lib/postgresql/data

volumes:
  pw1_rabbitmq_data:
    driver: local
  pw1_redis_data:
    driver: local
  pw1_postgres_data:
    driver: local